/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-01 04:54:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ohora;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fcomplete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/ohora/header.jsp", Long.valueOf(1730336729911L));
    _jspx_dependants.put("/ohora/footer.jsp", Long.valueOf(1730336729911L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/real/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730336729895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/cdn-main/join_complete.css\">\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.ohora.kr/web/upload/favicon_20190801113230.ico\" />\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("span.material-symbols-outlined {\r\n");
      out.write("	vertical-align: text-bottom;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("  <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"SP_topBanner\" style=\"display: block\">\r\n");
      out.write("      <div class=\"SP_layoutMin\">\r\n");
      out.write("        <div class=\"SP_topBn_inr\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"xans-element- xans-layout xans-layout-statelogoff\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"slide_banner_top slick-initialized slick-slider\"\r\n");
      out.write("            id=\"sltop_ban\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"slick-list draggable\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"slick-track\"\r\n");
      out.write("                style=\"\r\n");
      out.write("                  opacity: 1;\r\n");
      out.write("                  width: 1200px;\r\n");
      out.write("                  transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("                \"\r\n");
      out.write("              >\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"slick-slide slick-current slick-active\"\r\n");
      out.write("                  data-slick-index=\"0\"\r\n");
      out.write("                  aria-hidden=\"false\"\r\n");
      out.write("                  style=\"width: 1200px\"\r\n");
      out.write("                  tabindex=\"0\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a\r\n");
      out.write("                    href=\"/event/event6.html\"\r\n");
      out.write("                    tabindex=\"0\"\r\n");
      out.write("                    style=\"display: block\"\r\n");
      out.write("                    ><img\r\n");
      out.write("                      src=\"https://ohora.kr/optimize/images/pc/common/PC_header_lamp2.webp\"\r\n");
      out.write("                      style=\"width: 100%; display: block\"\r\n");
      out.write("                  /></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 회원 -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"fix_position\" class=\"modify ham_modify\">\r\n");
      out.write("      <div id=\"SMS_fixed_wrap\" class=\"SMS_fixed_wrap\">\r\n");
      out.write("        <div class=\"SP_top_wrap\">\r\n");
      out.write("          <div class=\"layout_Top\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-statelogoff SP_gnb_inr\"\r\n");
      out.write("            >\r\n");
      out.write("              <a href=\"/member/join_intro.html\"\r\n");
      out.write("                ><span class=\"title\">회원가입</span></a\r\n");
      out.write("              >|\r\n");
      out.write("              <a href=\"/member/login.html\" class=\"log\"\r\n");
      out.write("                ><span class=\"title\">로그인</span></a\r\n");
      out.write("              >\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"SMS_fixed_inner\">\r\n");
      out.write("          <div class=\"xans-element- xans-layout xans-layout-logotop fixed_logo\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/\"\r\n");
      out.write("              style=\"display: block; text-align: center; margin-top: 30px\"\r\n");
      out.write("            >\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"https://ohora.kr/web/upload/logo/ohora_BI_logotype_w.png\"\r\n");
      out.write("                style=\"margin-bottom: 7px\"\r\n");
      out.write("              />\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 헤더 주메뉴 -->\r\n");
      out.write("          <div class=\"gnb_menu_container\">\r\n");
      out.write("            <ul class=\"gnb_menu_wrap menu_1ul\">\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/product/list.html?cate_no=121\">new</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/product/list.html?cate_no=120\">best</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do\">product</a>\r\n");
      out.write("                <!-- 마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("                <ul class=\"menu_2ul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=160\"\r\n");
      out.write("                      ><span>네일</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=161\"\r\n");
      out.write("                      ><span>페디</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=470\"\r\n");
      out.write("                      ><span>커스텀</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=49\"\r\n");
      out.write("                      ><span>케어 &amp; 툴</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- //마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/product/list.html?cate_no=671\">outlet</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font\"><a href=\"/event/index.html\">event</a></li>\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"/board/gallery/list.html?board_no=13\">how to</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- //헤더 주메뉴 -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"icon_wrap\">\r\n");
      out.write("            <div class=\"small_icon search_fixed_btn\"></div>\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-orderbasketcount small_icon m_cart common_cart\"\r\n");
      out.write("            >\r\n");
      out.write("              <a href=\"/order/basket.html\"\r\n");
      out.write("                ><b class=\"count EC-Layout-Basket-count\">0</b></a\r\n");
      out.write("              >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"small_icon m_menu\"><a class=\"SMS_menu\"></a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        $(\".slide_banner_top\").slick({\r\n");
      out.write("          infinite: true,\r\n");
      out.write("          speed: 300,\r\n");
      out.write("          slidesToShow: 1,\r\n");
      out.write("          dots: false,\r\n");
      out.write("          arrows: false,\r\n");
      out.write("          autoplay: true,\r\n");
      out.write("          autoplaySpeed: 3000,\r\n");
      out.write("          swipe: true,\r\n");
      out.write("          pauseOnHover: false,\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<div class=\"layout-fix\">\r\n");
      out.write("			<div class=\"join-cp-title-wrap\">\r\n");
      out.write("			<div class=\"join-cp\"></div>\r\n");
      out.write("				<h2 class=\"join-cp-title-h2\">\r\n");
      out.write("					<span class=\"join-cp-title\">회원가입이 완료 되었습니다.</span>\r\n");
      out.write("				</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"join-cp-area\">\r\n");
      out.write("			<div class=\"join-cp-padding\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"default-join-cp\">\r\n");
      out.write("					<table class=\"join-cp-table\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"label\">아이디</td>\r\n");
      out.write("							<td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"label\">이 름</td>\r\n");
      out.write("							<td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"label\">이메일</td>\r\n");
      out.write("							<td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"join-cp-textbox\">\r\n");
      out.write("						<p>\r\n");
      out.write("							 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님은 [Friend] 등급입니다. <br /> 첫 구매시 오호라 젤램프를 받으실\r\n");
      out.write("							수 있습니다.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"btnArea\">\r\n");
      out.write("					<div class=\"btn\">\r\n");
      out.write("						<a href=\"../ohora/oho_main.jsp\">계속 쇼핑하기</a>\r\n");
      out.write("						<!-- 일단 main으로 보냈는데\r\n");
      out.write("						오호라는 여기로 날라감\r\n");
      out.write("						https://www.ohora.kr/product/list.html?cate_no=120&page_num=1-->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 아래로 추천상품 -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"reco-list-container\">\r\n");
      out.write("		<div class=\"text-area\">\r\n");
      out.write("			<h3 class=\"reco-text-h3\">추천 상품</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"reco-item-list\">\r\n");
      out.write("			<div class=\"item-container\">\r\n");
      out.write("				<ul class=\"item-list-ul\">\r\n");
      out.write("					<li class=\"reco-item\">\r\n");
      out.write("						<div class=\"item-div\">\r\n");
      out.write("							<!-- 여기 ::before 들어감-->\r\n");
      out.write("							<dl>\r\n");
      out.write("								<a href=\"\"></a>\r\n");
      out.write("								<div class=\"base-img\">\r\n");
      out.write("									<div class=\"thumb\">\r\n");
      out.write("										<img src=\"../image/cart_image/상품1.jpg\" alt=\"상품1\"\r\n");
      out.write("											class=\"thumbnail\" width=\"800\" height=\"800\" />\r\n");
      out.write("										<!-- hover에 관한건 알아서 만들어야하는듯 -->\r\n");
      out.write("										<img src=\"../image/cart_image/상품2.jpg\" alt=\"상품2\"\r\n");
      out.write("											class=\"hover_img\" width=\"800\" height=\"800\" /> <span\r\n");
      out.write("											class=\"sold-out\"></span>\r\n");
      out.write("										<!--품절 상품시에만 적용한다는데 안쓰는듯?-->\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"base-desc\">\r\n");
      out.write("									<dd class=\"info-container\">\r\n");
      out.write("										<p class=\"name\">\r\n");
      out.write("											<span>N 오닉스 네일</span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<dd class=\"price-container\">\r\n");
      out.write("										<p class=\"ori-price\">12,800</p>\r\n");
      out.write("										<p class=\"sale-price\">10,240</p>\r\n");
      out.write("										<p class=\"dcPercent\">20%</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"desc-bot\">\r\n");
      out.write("										<div class=\"bot-container\">\r\n");
      out.write("											<div class=\"bot-wrap\">\r\n");
      out.write("												<p class=\"rv_count-wrap\">\r\n");
      out.write("													<span class=\"rv-count\">3,520</span>\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"cart-container\">\r\n");
      out.write("										<img src=\"\" alt=\"\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</dl>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"reco-item\">\r\n");
      out.write("						<div class=\"item-div\">\r\n");
      out.write("							<!-- 여기 ::before 들어감-->\r\n");
      out.write("							<dl>\r\n");
      out.write("								<a href=\"\"></a>\r\n");
      out.write("								<div class=\"base-img\">\r\n");
      out.write("									<div class=\"thumb\">\r\n");
      out.write("										<img src=\"../image/cart_image/상품1.jpg\" alt=\"상품1\"\r\n");
      out.write("											class=\"thumbnail\" width=\"800\" height=\"800\" />\r\n");
      out.write("										<!-- hover에 관한건 알아서 만들어야하는듯 -->\r\n");
      out.write("										<img src=\"../image/cart_image/상품2.jpg\" alt=\"상품2\"\r\n");
      out.write("											class=\"hover_img\" width=\"800\" height=\"800\" /> <span\r\n");
      out.write("											class=\"sold-out\"></span>\r\n");
      out.write("										<!--품절 상품시에만 적용한다는데 안쓰는듯?-->\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"base-desc\">\r\n");
      out.write("									<dd class=\"info-container\">\r\n");
      out.write("										<p class=\"name\">\r\n");
      out.write("											<span>N 오닉스 네일</span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<dd class=\"price-container\">\r\n");
      out.write("										<p class=\"ori-price\">12,800</p>\r\n");
      out.write("										<p class=\"sale-price\">10,240</p>\r\n");
      out.write("										<p class=\"dcPercent\">20%</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"desc-bot\">\r\n");
      out.write("										<div class=\"bot-container\">\r\n");
      out.write("											<div class=\"bot-wrap\">\r\n");
      out.write("												<p class=\"rv_count-wrap\">\r\n");
      out.write("													<span class=\"rv-count\">3,520</span>\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"cart-container\">\r\n");
      out.write("										<img src=\"\" alt=\"\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</dl>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"reco-item\">\r\n");
      out.write("						<div class=\"item-div\">\r\n");
      out.write("							<!-- 여기 ::before 들어감-->\r\n");
      out.write("							<dl>\r\n");
      out.write("								<a href=\"\"></a>\r\n");
      out.write("								<div class=\"base-img\">\r\n");
      out.write("									<div class=\"thumb\">\r\n");
      out.write("										<img src=\"../image/cart_image/상품1.jpg\" alt=\"상품1\"\r\n");
      out.write("											class=\"thumbnail\" width=\"800\" height=\"800\" />\r\n");
      out.write("										<!-- hover에 관한건 알아서 만들어야하는듯 -->\r\n");
      out.write("										<img src=\"../image/cart_image/상품2.jpg\" alt=\"상품2\"\r\n");
      out.write("											class=\"hover_img\" width=\"800\" height=\"800\" /> <span\r\n");
      out.write("											class=\"sold-out\"></span>\r\n");
      out.write("										<!--품절 상품시에만 적용한다는데 안쓰는듯?-->\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"base-desc\">\r\n");
      out.write("									<dd class=\"info-container\">\r\n");
      out.write("										<p class=\"name\">\r\n");
      out.write("											<span>N 오닉스 네일</span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<dd class=\"price-container\">\r\n");
      out.write("										<p class=\"ori-price\">12,800</p>\r\n");
      out.write("										<p class=\"sale-price\">10,240</p>\r\n");
      out.write("										<p class=\"dcPercent\">20%</p>\r\n");
      out.write("									</dd>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"desc-bot\">\r\n");
      out.write("										<div class=\"bot-container\">\r\n");
      out.write("											<div class=\"bot-wrap\">\r\n");
      out.write("												<p class=\"rv_count-wrap\">\r\n");
      out.write("													<span class=\"rv-count\">3,520</span>\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"cart-container\">\r\n");
      out.write("										<img src=\"\" alt=\"\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</dl>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"next\"></div>\r\n");
      out.write("			<div class=\"prev\"></div>\r\n");
      out.write("			<div class=\"scrollBar\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("    <!-- 아래 필수 -->\r\n");
      out.write("    <div style=\"margin-top: 12%\"></div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("      <div class=\"chat\">\r\n");
      out.write("        <div class=\"top_left\">\r\n");
      out.write("          <span class=\"kakao_chat\">\r\n");
      out.write("            <a href=\"https://www.ohora.kr/etc/CS.html\"\r\n");
      out.write("              >카카오톡 상담 (@ohora)</a\r\n");
      out.write("            >\r\n");
      out.write("          </span>\r\n");
      out.write("          <span class=\"center_chat\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.ohora.kr/member/login.html?returnUrl=%2Fboard%2Fconsult%2Flist.html%3Fboard_no%3D9\"\r\n");
      out.write("              >게시판 상담 (1:1 문의하기)</a\r\n");
      out.write("            >\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"top_right\">\r\n");
      out.write("          <a href=\"https://www.instagram.com/ohora_official/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_insta.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://www.facebook.com/ohora.official\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_facebook.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://pf.kakao.com/_axjYfj\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_kakao.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://www.youtube.com/channel/UCV72a2QWRpEZjZYkWjXHZWQ\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_youtube.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://post.naver.com/my.nhn?memberNo=47439708\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_naver.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"a\">\r\n");
      out.write("          주문\r\n");
      out.write("          <div class=\"sub\" id=\"aa\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.ohora.kr/member/login.html?returnUrl=/myshop/order/list.html\"\r\n");
      out.write("              >주문·배송내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.ohora.kr/member/login.html?returnUrl=/myshop/order/list.html?mode=cs\"\r\n");
      out.write("              >취소/교환/반품내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a href=\"https://www.ohora.kr/order/basket.html\">장바구니</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"b\">\r\n");
      out.write("          회원\r\n");
      out.write("          <div class=\"sub\" id=\"bb\">\r\n");
      out.write("            <a href=\"#\">신규 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"#\">멤버십 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"#\">마이페이지</a><br /><br />\r\n");
      out.write("            <a href=\"#\">적립금·쿠폰내역</a><br /><br />\r\n");
      out.write("            <a href=\"#\">회원정보변경</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"c\">\r\n");
      out.write("          서비스\r\n");
      out.write("          <div class=\"sub\" id=\"cc\">\r\n");
      out.write("            <a href=\"#\">FAQ</a><br /><br />\r\n");
      out.write("            <a href=\"#\">상담톡</a><br /><br />\r\n");
      out.write("            <a href=\"#\">사용법</a><br /><br />\r\n");
      out.write("            <a href=\"#\">공지사항</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"company\" style=\"margin-top: 10px; margin-bottom: 10px;\">\r\n");
      out.write("        <p>\r\n");
      out.write("          대표 : 유기현<br />\r\n");
      out.write("          회사 : 주식회사 글루가<br />\r\n");
      out.write("          주소 : 충남 천안시 서북구 2공단8길 45 2층 (업성동)<br />\r\n");
      out.write("          사업자등록번호 : 722-87-00061<br />\r\n");
      out.write("          통신판매업신고번호 : 2017-충남천안-1055호 사업자 정보 확인<br />\r\n");
      out.write("          개인정보처리담당자 : 유태규<br />\r\n");
      out.write("          고객센터 : 1566-0554<br />\r\n");
      out.write("          평일 09:00~18:00 (Lunch 12:30~13:30)<br />\r\n");
      out.write("          영업문의 : ohora_official@ohora.com<br />\r\n");
      out.write("          제휴 & 파트너십 문의 : ohora_partnership@ohora.com<br />\r\n");
      out.write("          글로벌 제휴 & 파트너십 문의 : Global-Business@ohora.com\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"bottom\">\r\n");
      out.write("        <span class=\"a\"><a href=\"#\">브랜드 소개</a></span>\r\n");
      out.write("        <span class=\"b\"><a href=\"#\">이용약관</a></span>\r\n");
      out.write("        <span class=\"c\"><a href=\"#\">개인정보처리방침</a></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script>\r\n");
      out.write("  let sw = true;\r\n");
      out.write("  \r\n");
      out.write("  let a = document.querySelector(\"#a\");\r\n");
      out.write("  let aa = document.querySelector(\"#aa\");\r\n");
      out.write("  a.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        aa.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        aa.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let b = document.querySelector(\"#b\");\r\n");
      out.write("  let bb = document.querySelector(\"#bb\");\r\n");
      out.write("  b.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        bb.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        bb.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let c = document.querySelector(\"#c\");\r\n");
      out.write("  let cc = document.querySelector(\"#cc\");\r\n");
      out.write("  c.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        cc.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        cc.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
